import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { cookies } from "next/headers";
import Darkmode from "./Darkmode";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  //서버컴포넌트에서 로그인 유저정보 출력. 만약 client에서 사용하려면   let session  = useSession(); 식으로 사용하면 된다.
  const session = await getServerSession(authOptions);
  // console.log(session);

  let cookie = cookies().get("mode").value;
  console.log(cookie);

  return (
    <html lang="en">
      <body
        className={
          cookie !== "undefined" && cookie == "dark" ? "dark-mode" : ""
        }
      >
        <div className="navbar">
          <Link href="/" className="logo">
            용포럼
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <div className="rightNav">
            {session ? (
              <>
                <span>{session.user.name}</span> <LogoutBtn />
              </>
            ) : (
              <LoginBtn />
            )}
            <Darkmode mode={cookie} />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
